import com.jw.edge.entity.Terminal
import com.jw.edge.controller.api.WebDataController
import com.jw.edge.controller.api.TerminalDataController

rule "温度大于1"
when    $terminal : Terminal(terminal_value>=drools_threshold && drools_parameterName=="0" && drools_symbol=="0")
then        $terminal.setFlag1(1);
end

rule "温度小于1"
when    $terminal : Terminal(terminal_value<drools_threshold && drools_parameterName=="0" && drools_symbol=="1")
then        $terminal.setFlag1(1);
end

rule "湿度大于1"
when    $terminal : Terminal(terminal_value>=drools_threshold && drools_parameterName=="1" && drools_symbol=="0")
then        $terminal.setFlag1(1);
end

rule "湿度小于1"
when    $terminal : Terminal(terminal_value<drools_threshold && drools_parameterName=="1" && drools_symbol=="1")
then        $terminal.setFlag1(1);
end

rule "温度大于2"
when    $terminal2 : Terminal(terminal_value>=drools_threshold2 && drools_parameterName2=="0" && drools_symbol2=="0")
then        $terminal2.setFlag2(1);
end

rule "温度小于2"
when    $terminal2 : Terminal(terminal_value<drools_threshold2 && drools_parameterName2=="0" && drools_symbol2=="1")
then        $terminal2.setFlag2(1);
end

rule "湿度大于2"
when    $terminal2 : Terminal(terminal_value>=drools_threshold2 && drools_parameterName2=="1" && drools_symbol2=="0")
then        $terminal2.setFlag2(1);
end

rule "湿度小于2"
when    $terminal2 : Terminal(terminal_value<drools_threshold2 && drools_parameterName2=="1" && drools_symbol2=="1")
then        $terminal2.setFlag2(1);
end

rule "温度大于3"
when    $terminal3 : Terminal(terminal_value>=drools_threshold3 && drools_parameterName3=="0" && drools_symbol3=="0")
then        $terminal3.setFlag3(1);
end

rule "温度小于3"
when    $terminal3 : Terminal(terminal_value<drools_threshold3 && drools_parameterName3=="0" && drools_symbol3=="1")
then        $terminal3.setFlag3(1);
end

rule "湿度大于3"
when    $terminal3 : Terminal(terminal_value>=drools_threshold3 && drools_parameterName3=="1" && drools_symbol3=="0")
then        $terminal3.setFlag3(1);
end

rule "湿度小于3"
when    $terminal3 : Terminal(terminal_value<drools_threshold3 && drools_parameterName3=="1" && drools_symbol3=="1")
then        $terminal3.setFlag3(1);
end