import com.jw.edge.entity.Terminal
import com.jw.edge.controller.api.WebDataController
import com.jw.edge.controller.api.TerminalDataController

rule "温度大于1"
when    $terminal : Terminal(terminal_value>=drools_threshold && drools_parameterName=="0" && drools_symbol=="0")
then        $terminal.setFlag1(1);
end
rule "温度小于1"
when    $terminal : Terminal(terminal_value<drools_threshold && drools_parameterName=="0" && drools_symbol=="1")
then        $terminal.setFlag1(1);
end
rule "湿度大于1"
when    $terminal : Terminal(terminal_value>=drools_threshold && drools_parameterName=="1" && drools_symbol=="0")
then        $terminal.setFlag1(1);
end
rule "湿度小于1"
when    $terminal : Terminal(terminal_value<drools_threshold && drools_parameterName=="1" && drools_symbol=="1")
then        $terminal.setFlag1(1);
end

rule "温度大于2"
when    $terminal2 : Terminal(terminal_value>=drools_threshold2 && drools_parameterName2=="0" && drools_symbol2=="0")
then        $terminal2.setFlag2(1);
end
rule "温度小于2"
when    $terminal2 : Terminal(terminal_value<drools_threshold2 && drools_parameterName2=="0" && drools_symbol2=="1")
then        $terminal2.setFlag2(1);
end
rule "湿度大于2"
when    $terminal2 : Terminal(terminal_value>=drools_threshold2 && drools_parameterName2=="1" && drools_symbol2=="0")
then        $terminal2.setFlag2(1);
end
rule "湿度小于2"
when    $terminal2 : Terminal(terminal_value<drools_threshold2 && drools_parameterName2=="1" && drools_symbol2=="1")
then        $terminal2.setFlag2(1);
end

rule "温度大于3"
when    $terminal3 : Terminal(terminal_value>=drools_threshold3 && drools_parameterName3=="0" && drools_symbol3=="0")
then        $terminal3.setFlag3(1);
end
rule "温度小于3"
when    $terminal3 : Terminal(terminal_value<drools_threshold3 && drools_parameterName3=="0" && drools_symbol3=="1")
then        $terminal3.setFlag3(1);
end
rule "湿度大于3"
when    $terminal3 : Terminal(terminal_value>=drools_threshold3 && drools_parameterName3=="1" && drools_symbol3=="0")
then        $terminal3.setFlag3(1);
end
rule "湿度小于3"
when    $terminal3 : Terminal(terminal_value<drools_threshold3 && drools_parameterName3=="1" && drools_symbol3=="1")
then        $terminal3.setFlag3(1);
end

rule "温度大于4"
when    $terminal4 : Terminal(terminal_value>=drools_threshold4 && drools_parameterName4=="0" && drools_symbol4=="0")
then        $terminal4.setFlag4(1);
end
rule "温度小于4"
when    $terminal4 : Terminal(terminal_value<drools_threshold4 && drools_parameterName4=="0" && drools_symbol4=="1")
then        $terminal4.setFlag4(1);
end
rule "湿度大于4"
when    $terminal4 : Terminal(terminal_value>=drools_threshold4 && drools_parameterName4=="1" && drools_symbol4=="0")
then        $terminal4.setFlag4(1);
end
rule "湿度小于4"
when    $terminal4 : Terminal(terminal_value<drools_threshold4 && drools_parameterName4=="1" && drools_symbol4=="1")
then        $terminal4.setFlag4(1);
end

rule "温度大于5"
when    $terminal5 : Terminal(terminal_value>=drools_threshold5 && drools_parameterName5=="0" && drools_symbol5=="0")
then        $terminal5.setFlag5(1);
end
rule "温度小于5"
when    $terminal5 : Terminal(terminal_value<drools_threshold5 && drools_parameterName5=="0" && drools_symbol5=="1")
then        $terminal5.setFlag5(1);
end
rule "湿度大于5"
when    $terminal5 : Terminal(terminal_value>=drools_threshold5 && drools_parameterName5=="1" && drools_symbol5=="0")
then        $terminal5.setFlag5(1);
end
rule "湿度小于5"
when    $terminal5 : Terminal(terminal_value<drools_threshold5 && drools_parameterName5=="1" && drools_symbol5=="1")
then        $terminal5.setFlag5(1);
end

rule "温度大于6"
when    $terminal6 : Terminal(terminal_value>=drools_threshold6 && drools_parameterName6=="0" && drools_symbol6=="0")
then        $terminal6.setFlag6(1);
end
rule "温度小于6"
when    $terminal6 : Terminal(terminal_value<drools_threshold6 && drools_parameterName6=="0" && drools_symbol6=="1")
then        $terminal6.setFlag6(1);
end
rule "湿度大于6"
when    $terminal6 : Terminal(terminal_value>=drools_threshold6 && drools_parameterName6=="1" && drools_symbol6=="0")
then        $terminal6.setFlag6(1);
end
rule "湿度小于6"
when    $terminal6 : Terminal(terminal_value<drools_threshold5 && drools_parameterName5=="1" && drools_symbol6=="1")
then        $terminal6.setFlag6(1);
end

rule "温度大于7"
when    $terminal7 : Terminal(terminal_value>=drools_threshold7 && drools_parameterName7=="0" && drools_symbol7=="0")
then        $terminal7.setFlag7(1);
end
rule "温度小于7"
when    $terminal7 : Terminal(terminal_value<drools_threshold7 && drools_parameterName7=="0" && drools_symbol7=="1")
then        $terminal7.setFlag7(1);
end
rule "湿度大于7"
when    $terminal7 : Terminal(terminal_value>=drools_threshold7 && drools_parameterName7=="1" && drools_symbol7=="0")
then        $terminal7.setFlag7(1);
end
rule "湿度小于7"
when    $terminal7 : Terminal(terminal_value<drools_threshold7 && drools_parameterName7=="1" && drools_symbol7=="1")
then        $terminal7.setFlag7(1);
end

rule "温度大于8"
when    $terminal8 : Terminal(terminal_value>=drools_threshold8 && drools_parameterName8=="0" && drools_symbol8=="0")
then        $terminal8.setFlag8(1);
end
rule "温度小于8"
when    $terminal8 : Terminal(terminal_value<drools_threshold8 && drools_parameterName8=="0" && drools_symbol8=="1")
then        $terminal8.setFlag8(1);
end
rule "湿度大于8"
when    $terminal8 : Terminal(terminal_value>=drools_threshold8 && drools_parameterName8=="1" && drools_symbol8=="0")
then        $terminal8.setFlag8(1);
end
rule "湿度小于8"
when    $terminal8 : Terminal(terminal_value<drools_threshold8 && drools_parameterName8=="1" && drools_symbol8=="1")
then        $terminal8.setFlag8(1);
end

rule "温度大于9"
when    $terminal9 : Terminal(terminal_value>=drools_threshold9 && drools_parameterName9=="0" && drools_symbol9=="0")
then        $terminal9.setFlag9(1);
end
rule "温度小于9"
when    $terminal9 : Terminal(terminal_value<drools_threshold9 && drools_parameterName9=="0" && drools_symbol9=="1")
then        $terminal9.setFlag9(1);
end
rule "湿度大于9"
when    $terminal9 : Terminal(terminal_value>=drools_threshold9 && drools_parameterName9=="1" && drools_symbol9=="0")
then        $terminal9.setFlag9(1);
end
rule "湿度小于9"
when    $terminal9 : Terminal(terminal_value<drools_threshold9 && drools_parameterName9=="1" && drools_symbol9=="1")
then        $terminal9.setFlag9(1);
end

rule "温度大于10"
when    $terminal10 : Terminal(terminal_value>=drools_threshold10 && drools_parameterName10=="0" && drools_symbol10=="0")
then        $terminal10.setFlag10(1);
end
rule "温度小于10"
when    $terminal10 : Terminal(terminal_value<drools_threshold10 && drools_parameterName10=="0" && drools_symbol10=="1")
then        $terminal10.setFlag10(1);
end
rule "湿度大于10"
when    $terminal10 : Terminal(terminal_value>=drools_threshold10 && drools_parameterName10=="1" && drools_symbol10=="0")
then        $terminal10.setFlag10(1);
end
rule "湿度小于10"
when    $terminal10 : Terminal(terminal_value<drools_threshold10 && drools_parameterName10=="1" && drools_symbol10=="1")
then        $terminal10.setFlag10(1);
end